import React, { useCallback, useEffect, useState } from "react";
import Layout from "../components/layout";
import { User } from "@supabase/supabase-js";
import { GetServerSidePropsContext, NextPage } from "next";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import axios from "axios";
import { toast } from "react-hot-toast";
import Plans from "../components/plans";
import Stripe from "stripe";
import Counter from "../components/counter";
import { protocol } from "../lib/sanitizer";
import ApiKey from "../components/api-key";
